# Generated by Django 5.1.2 on 2024-10-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_code',
            field=models.CharField(default='EAC09853C9', max_length=10, unique=True),
        ),
    ]
