name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff black # Instalacja Ruff i Black
    
    - name: Run Ruff (static analysis)
      run: |
        ruff check . --fix --exit-zero  # Uruchomienie Ruff na całym projekcie z automatycznym poprawieniem kodu
    
    - name: Run Black (code formatting)
      run: |
        black . --check --diff  # Sprawdzenie, czy kod jest zgodny z formatowaniem Blacka
    
    - name: Build Docker Image
      run: |
        docker build -t url_shortener .  # Zbudowanie obrazu Docker
    
    - name: Run Tests
      run: |
        docker run --rm url_shortener python manage.py test  # Uruchomienie testów w kontenerze Docker
